# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Open Geo Tools
email: your-email@domain.com
description: A survey on capabilities and functionalities of open geo tools. Companion to our abstract at the German Cartography conference.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://fh-potsdam.github.io/OpenGeoTools/" # the base hostname & protocol for your site
twitter_username: seb_meier
github_username:  sebastian-meier

# URL settings
url: "http://127.0.0.1:4000/"
bootstrap-url: "https://maxcdn.bootstrapcdn.com/bootstrap/"
jquery-url: "https://code.jquery.com/"
d3-url: "https://cdnjs.cloudflare.com/"

include: [tools]

# Build settings
markdown: kramdown
syntax_highlighter: rouge
