# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Open Geo Tools
email: your-email@domain.com
description: A survey on capabilities and functionalities of open geo tools. Companion to our abstract at the German Cartography conference.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fh-potsdam.github.io/OpenGeoTools/" # the base hostname & protocol for your site
twitter_username: seb_meier
github_username:  sebastian-meier

include: [tools]

# Build settings
markdown: kramdown
